### ISSUE TITLE
`bosh update cli` fails

### ISSUE THREAD

**Issue by brandonzylstra** [cloudfoundry-community/traveling-bosh#8]
`bosh update cli` fails since  `curl` receives a response of 'Not Found' from [githubusercontent.com](https://raw.githubusercontent.com/cloudfoundry-community/bosh_cli_install/master/binscripts/installer), which (when piped to `bash`) results in `bash: line 1: Not: command not found`, as seen below:

```
➲ bosh update cli
curl -k -s https://raw.githubusercontent.com/cloudfoundry-community/bosh_cli_install/master/binscripts/installer | bash
bash: line 1: Not: command not found
/Users/brandon/bin/traveling-bosh/lib/vendor/ruby/2.1.0/gems/rake-10.4.2/lib/rake/file_utils.rb:66:in `block in create_shell_runner': Command failed with status (127): [curl -k -s https://raw.githubusercontent.c...] (RuntimeError)
    from /Users/brandon/bin/traveling-bosh/lib/vendor/ruby/2.1.0/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `call'
    from /Users/brandon/bin/traveling-bosh/lib/vendor/ruby/2.1.0/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `sh'
    from /Users/brandon/bin/traveling-bosh/lib/vendor/ruby/2.1.0/gems/traveling_bosh_cli_plugin-1.0.0/lib/bosh/cli/commands/update_traveling_ruby.rb:12:in `update_cli'
    from /Users/brandon/bin/traveling-bosh/lib/vendor/ruby/2.1.0/gems/bosh_cli-1.2809.0/lib/cli/command_handler.rb:57:in `run'
    from /Users/brandon/bin/traveling-bosh/lib/vendor/ruby/2.1.0/gems/bosh_cli-1.2809.0/lib/cli/runner.rb:56:in `run'
    from /Users/brandon/bin/traveling-bosh/lib/vendor/ruby/2.1.0/gems/bosh_cli-1.2809.0/lib/cli/runner.rb:16:in `run'
    from /Users/brandon/bin/traveling-bosh/lib/vendor/ruby/2.1.0/gems/bosh_cli-1.2809.0/bin/bosh:7:in `<top (required)>'
    from /Users/brandon/bin/traveling-bosh/lib/vendor/ruby/2.1.0/bin/bosh:23:in `load'
    from /Users/brandon/bin/traveling-bosh/lib/vendor/ruby/2.1.0/bin/bosh:23:in `<main>'
```

**Comment by drnic** [comment]
Ok, looks like I moved the installer back into traveling-bosh repo but
didn't update the updater. Genius :)

https://raw.githubusercontent.com/cloudfoundry-community/traveling-bosh/master/scripts/installer

**Comment by drnic** [comment]
BTW, fixes to traveling-bosh are blocked at the moment - I accidentally broke my build setup (various branches of bosh repo) and need to make time to reconstruct them (or discover if they are no longer required). They were to allow newer upstream rubygem dependencies that were available with traveling-ruby.
